### ISSUE TITLE
No login any more to https://bitbucket.hdfgroup.org/projects

### ISSUE THREAD

**Issue by grib2user** [NOAA-EMC/NCEPLIBS-external#102]
Hi,

During standard making/installation, make process for NCEPLIBS-external attempts to login to https://bitbucket.hdfgroup.org/ which is not longer possible. They moved everything to github. HDF5 now is on github too, so a quick link update is needed.

Try yourself.

See also this: https://forum.hdfgroup.org/t/hdf4-repository-moved-removed-protected/8289

Thank you for your attention to this matter,
Hope for a quick resolution,

**Comment by edwardhartnett** [comment]
NCEPLIBS-external is deprecated and no longer supported.

Instead, install the necessary libraries and utilities individually, according to their individual instructions.
