### ISSUE TITLE
wgrib2 uses GCC to build Jasper even when using Intel

### ISSUE THREAD

**Issue by kgerheiser** [NOAA-EMC/NCEPLIBS-external#27]

**Comment by kgerheiser** [comment]
Doesn't appear to be an easy workaround, and wgrib2 doesn't even build with icc.

**Comment by climbfuji** [comment]
Can we then close this issue? Since wgrib2 and the libraries are linked statically, they are completely independent and encapsulated from the rest of the build. I understand this means that we still require a 21st century GNU compiler, but I think it is fair to do so.
