### ISSUE TITLE
Linking to libz - netCDF and libpng

### ISSUE THREAD

**Issue by climbfuji** [NOAA-EMC/NCEPLIBS-external#28]
If the NetCDF build is turned off (-DBUILD_NETCDF=OFF) but LIBPNG is going to be built, there is a potential issue downstream when building the NCEPLIBS.

This is because building LIBPNG is triggering the build of LIBZ (and then using this version), whereas NetCDF is linking against another version of LIBZ (very often the default OS version, at least on NOAA and TACC platforms). 

It seems to me that if we are not building netCDF (or not building libpng) but still building the other library, we need to use the libz version that the existing library is linked against. Even if the  conflict doesn't show up during the cmake step (because the libz version the existing library is linked against is not in the library path), it can cause issues during the make step.

Any idea how to implement this without too much hardcoding would be appreciated.

**Comment by climbfuji** [comment]
Also tagging @aerorahul in case you have any ideas on this one.

**Comment by mark-a-potts** [comment]
It looks like netcdf only uses zlib when HDF4 is enabled. Maybe we can just disable that (does anything in the UFS suite require HDF4?) and then we only have one zlib linked no matter what.

**Comment by aerorahul** [comment]
@climbfuji @mark-a-potts In my opinion, the `FindNetCDF.cmake` that is in cmake/Modules is deficient in many ways. 

In JEDI development, we have been using a modification with success on a number of platforms.
Consider replacing the FindNetCDF.cmake with [this](https://github.com/JCSDA/ecbuild/blob/release/stable/cmake/contrib/FindNetCDF4.cmake).  This version relies on `nc-config` to determine the flags (and dependencies), rather than looking for each individual file using `find_path`.  This is especially troublesome, when building with custom libraries e.g. openssl, curl, etc., as is done in the NASA GEOS model.

**Comment by climbfuji** [comment]
@aerorahul point taken, but this is independent of the issue here. @mark-a-potts hdf5 uses zlib "behind" the scenes". Won't you still have the issue with different libz when everything comes together when linking the executable?

**Comment by aerorahul** [comment]
I don't think so, because `nc-config` knows how netCDF was built and linked. This includes the HDF flags. A simple swap and test would tell us quickly.

One problem that may have been overlooked here is that if NetCDF is built with cmake, it does not produce the nc-config file correctly.

**Comment by climbfuji** [comment]
So how do we get this information on which zlib was used from netcdf to the libpng build?

**Comment by aerorahul** [comment]
"So how do we get this information on which zlib was used from netcdf to the libpng build?"
I don't think that is possible. Why would you pass flags/libs from netcdf build to libpng? libpng is such a basic library.

IMHO, zlib, png, jpeg, jasper etc. should be users responsibility to locate/build. In fact, the whole external libs is (should be) the users responsibility. 
We are talking about libraries that have well supported documentation and build procedures. 
But, that ship has sailed.

I don't use the NCEPLibs-externals, so I am ignoring what is inside it.  I am testing the NCEPLIBS with the NCEPLibs-externals, but that is it.

**Comment by climbfuji** [comment]
Alright. The solution will then be to either build both netcdf and libpng or none of them.
