### ISSUE TITLE
Use configure/make/make install instead of cmake build for NetCDF

### ISSUE THREAD

**Issue by climbfuji** [NOAA-EMC/NCEPLIBS-external#45]
The NetCDF cmake build system called by the NCEPLIBS-external build system is not yet mature and causes problems down the road (for example, the results from querying nc-config or nf-config are incorrect).

We should move to a traditional configure/make/make install build for NetCDF (and probably others : zlib, hdf5, jasper, libpng, jpeg) until the cmake builds are matured.

**Comment by edwardhartnett** [comment]
Well the cmake build for netcdf-c and netcdf-fortran is pretty mature these days. As the author of the autotools build for those packages, of course I prefer my own work and always use autotools. But I also help maintain the cmake builds (authored by Ward) and they seem to work well.

There have been some recent fixes of nf-config in the cmake build, IIRC. If there is still a problem, please let me know and we can open and issue and get it fixed.

**Comment by kgerheiser** [comment]
Done
