### ISSUE TITLE
make test should work, and should run tests of component packages

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-external#49]
One big concern I have, as a netCDF developer, is that you are enabling people to install netCDF and not run the tests. That's bad.

There are a non-trivial number of systems for which the tests will reveal a problem which must be addressed. One question we always ask anyone who is seeking netCDF support with a mysterious problem: "Did the netCDF test suite succeed?"

So it would be great if NCEPLIB-externals could have a functioning make test target, which would run the make test target of the component packages.

**Comment by kgerheiser** [comment]
Added that 

https://github.com/NOAA-EMC/NCEPLIBS-external/pull/52
