### ISSUE TITLE
new version of netcdf-c available, but netcdf-fortran is not yet available...

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-external#50]
I actually think you should remove netCDF and the whole I/O stack from this repo.

However, if you are planning on keeping them, note that there is a new version of netcdf-c, 4.7.4, and that new version is required for the GFS v16 since it provides parallel zlib writes.

Normally we (netcdf programmers) try to keep everything backwards and forwards compatible, so that various versions of netcdf-c and netcdf-fortran will work together. That's not true in this case. Once a user switches to netcdf-c-4.7.4, older versions of netcdf-fortran will no longer work.

Unfortunately, there has not yet been a release of netcdf-fortran since 4.7.4, so there is currently no released netcdf-fortran which works with the current netcdf-c release. However, I expect Ward will put out a new netcdf-fortran release soon (see https://github.com/Unidata/netcdf-fortran/issues/248).

So you should not update netcdf-c until netcdf-fortran is formally released.

**Comment by climbfuji** [comment]
@edwardhartnett I just updated to netcdf-c-4.7.4 and netcdf-fortran-4.5.3. Can you confirm that these two play together nicely?

**Comment by edwardhartnett** [comment]
Yes, that is correct, the netcdf-fortran release was made, and now there is a netcdf-fortran that works with the netcdf-c-4.7.4 release. ;-)

I will close this ticket.

**Comment by climbfuji** [comment]
Thanks, @edwardhartnett !

**Comment by edwardhartnett** [comment]
BTW these versions will be required for the parallel compression code to work. Previous versions of netCDF will give an error when the code tries to set deflation for a variable in a file opened/created with parallel I/O. (I see I already explained that above. ;-))
