### ISSUE TITLE
Instructions for stampede are out of date 

### ISSUE THREAD

**Issue by jedwards4b** [NOAA-EMC/NCEPLIBS-external#53]
git/2.9.0 and xalt/2.7.9 are no longer available on the system.

**Comment by kgerheiser** [comment]
Do you know what the new ones are? I'd be happy to update it.

**Comment by jedwards4b** [comment]
Stampede is down for maintenance today, I'll check tomorrow.

**Comment by jedwards4b** [comment]
Currently available: 

 git/2.24.1 
 xalt/2.8

**Comment by climbfuji** [comment]
This has been fixed with the recent commits in preparation for MRW v1.1.
