### ISSUE TITLE
hdf5 clone fails due to needing bitbucket authentication

### ISSUE THREAD

**Issue by mkavulich** [NOAA-EMC/NCEPLIBS-external#79]
I believe this is new behavior; I have cloned NCEPLIBS-external successfully in the past without a bitbucket account. I'm not sure if this means that cloning is restricted to certain accounts or just any bitbucket account will do.

**Comment by mkavulich** [comment]
This is the URL that requires login: https://bitbucket.hdfgroup.org/scm/hdffv/hdf5.git/

**Comment by climbfuji** [comment]
Is there another link we can use? Have they moved to something else? Or can we use anonymous login like in the good old days for ftp?

**Comment by kgerheiser** [comment]
It shouldn't require an account. Perhaps it's the specific machine you're using? Some block bitbuck (and not Github)

**Comment by climbfuji** [comment]
> It shouldn't require an account. Perhaps it's the specific machine you're using? Some block bitbuck (and not Github)

Good point, which machine?

**Comment by edwardhartnett** [comment]
The link works on the command line for me, so the repo is there and available.

**Comment by mkavulich** [comment]
There must have been some sort of change to their bitbucket repository; it was not working on Tuesday or yesterday morning either through the browser or the command line (tried on multiple machines), but it seems to be working now (the above html link now works as well). Closing this issue.
