### ISSUE TITLE
Cannot clone the correct file on HPC 

### ISSUE THREAD

**Issue by Minghua-Zheng-DA** [NOAA-EMC/NCEPLIBS-external#89]
Dear coder manager, 
I tried to install this on San Diego Super Computer and received the following errors when using the command: 
git clone -b ufs-v1.1.0 --recursive https://github.com/NOAA-EMC/NCEPLIBS-external

_Cloning into 'minghua/Models/GSI/NCEPLIBS-external/esmf'...
fatal: unable to access 'https://git.code.sf.net/p/esmf/esmf/': Failed connect to git.code.sf.net:443; Connection timed out
fatal: clone of 'https://git.code.sf.net/p/esmf/esmf' into submodule path '/minghua/Models/GSI/NCEPLIBS-external/esmf' failed
Failed to clone 'esmf' a second time, aborting_

Could you please advise how to resolve this issue? Thank you in advance for your time.

- Minghua

**Comment by climbfuji** [comment]
I've had this problem as well in the past on another machine. Unless that URL is blocked by your firewall, It sometimes works, sometimes times out. Try the following:
```
git clone -b ufs-v1.1.0 https://github.com/NOAA-EMC/NCEPLIBS-external
cd NCEPLIBS-external
git submodule update --init --recursive esmf # repeat if timeout
git submodule update --iniit --recursive # this takes care of the rest
```

**Comment by Minghua-Zheng-DA** [comment]
> I've had this problem as well in the past on another machine. Unless that URL is blocked by your firewall, It sometimes works, sometimes times out. Try the following:
> 
> ```
> git clone -b ufs-v1.1.0 https://github.com/NOAA-EMC/NCEPLIBS-external
> cd NCEPLIBS-external
> git submodule update --init --recursive esmf # repeat if timeout
> git submodule update --iniit --recursive # this takes care of the rest
> ```

Thank you so much for the comments. Seem to be working now.
