### ISSUE TITLE
mac install problem

### ISSUE THREAD

**Issue by fipoucat** [NOAA-EMC/NCEPLIBS-external#97]
Could someone help building these libs of a mac? I am getting the below error when running cmake

-- Detecting CXX compile features - done
-- Building libraries: NETCDF ESMF JASPER PNG WGRIB2 
-- Found MPI_C: /Users/sarr/work/Build_WRF/LIBS/mpich/lib/libmpi.dylib (found version "3.1") 
-- Could NOT find MPI_CXX (missing: MPI_CXX_WORKS) 
-- Found MPI_Fortran: /Users/sarr/work/Build_WRF/LIBS/mpich/lib/libmpifort.dylib (found version "3.1") 
CMake Error at /usr/local/Cellar/cmake/3.22.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find MPI (missing: MPI_CXX_FOUND) (found version "3.1")
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.22.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.22.1/share/cmake/Modules/FindMPI.cmake:1830 (find_package_handle_standard_args)
  CMakeLists.txt:77 (find_package)
Thanks

**Comment by edwardhartnett** [comment]
I strongly suggest that you not use NCEPLIBS-external and instead install each of these packages individually, following the instructions of each project.

NCEPLIBS-external was misguided and is being deprecated. NOAA cannot be responsible for the build systems of these external projects.

Moving forward, a better solution would be to use spack. All of the NCEPLIBS-external packages are already supported by spack: https://spack.io/

**Comment by fipoucat** [comment]
Thank you for the spack suggestion, I'll give it a try.
